players:
  min: 2
  max: 10

# Timing values expressed in seconds.
timers:
  auto-start-seconds: 120
  hunter-selection-seconds: 10
  game-duration-seconds: 600
  runner-respawn-seconds: 5
  respawn-invulnerability-seconds: 2

sudden-death:
  enabled: true
  start-seconds: 120
  reveal-interval-seconds: 20
  reveal-duration-seconds: 5
  hunter-speed-amplifier: 1

scales:
  runner: 0.33
  hunter: 1.0

areas:
  lobby: {}

arenas: {}

active-arena: ""

messages:
  command-help: |
    &6Comandi TinyHunt:
    &e/tinyhunt join&7 - Apri il menu della lobby.
    &e/tinyhunt leave&7 - Lascia la coda o la partita.
    &e/tinyhunt lobby setpos1|setpos2&7 - Definisci gli angoli della lobby.
    &e/tinyhunt arena create&7 - Avvia la creazione di una nuova arena.
    &e/tinyhunt arena set <nome>&7 - Ricevi la wand per delimitare l'arena.
    &e/tinyhunt arena spawn <nome>&7 - Aggiungi uno spawn all'arena.
    &e/tinyhunt start&7 - Forza l'avvio quando pronto.
    &e/tinyhunt stop&7 - Ferma la partita in corso.
  unknown-subcommand: "&cComando sconosciuto. Usa &e/tinyhunt&c per aiuto."
  player-only: "&cSolo i giocatori possono usare questo comando."
  no-permission: "&cNon hai il permesso per farlo."
  cannot-join: "&cNon puoi unirti ora, la partita è già in corso."
  already-queued: "&eSei già in coda."
  queue-full: "&cLa coda è piena."
  joined-queue: "&aEntrato in coda! Posizione: &e%position%&a."
  left-queue: "&eHai lasciato la coda."
  not-in-queue: "&cNon sei in coda."
  countdown-start: "&aNumero minimo raggiunto! Avvio tra &e%seconds% &asecondi."
  countdown-tick: "&eLa partita inizia tra &6%seconds% &esecondi."
  countdown-cancelled: "&cConto alla rovescia annullato: giocatori insufficienti."
  not-enough-players: "&cServono più giocatori per iniziare la partita."
  configuration-missing: "&cConfigura lobby, arena e spawn prima di avviare il gioco."
  game-start: "&aLa partita è iniziata!"
  already-running: "&eUna partita è già in corso."
  hunter-selected: "&c%player% &eè diventato l'Hunter!"
  you-are-hunter: "&cSei l'Hunter! Caccia tutti i runner."
  now-hunter: "&cSei stato trasformato in Hunter!"
  runner-converted: "&c%player% &eè stato convertito in Hunter."
  runner-respawn-start: "&6Sei stato preso! Tornerai come Hunter tra &e%seconds%s&6."
  runner-respawn-broadcast: "&e%player% &6tornerà come Hunter tra &e%seconds%s&6."
  runner-respawn-complete: "&cSei tornato come Hunter!"
  hunters-win: "&cGli Hunter hanno eliminato tutti i Runner!"
  runners-win: "&aI Runner hanno resistito abbastanza a lungo!"
  manual-stop: "&eLa partita è stata fermata manualmente."
  start-requested: "&aRichiesta di avvio forzato inviata."
  stop-requested: "&eRichiesta di stop inviata."
  no-active-game: "&cNon c'è nessuna partita da fermare."
  reloaded: "&aConfigurazione ricaricata."
  usage-lobby: "&eUsa: /tinyhunt lobby setpos1|setpos2"
  usage-arena: "&eUsa: /tinyhunt arena create|set <nome>|spawn <nome>"
  lobby-pos-set: "&aAngolo &e%corner% &adella lobby salvato."
  arena-pos-set: "&aArena &e%arena%&a: angolo &e%corner% &asalvato."
  arena-spawn-added: "&aSpawn aggiunto all'arena &e%arena%&a."
  arena-name-prompt: "&eScrivi in chat il nome della nuova arena (verrà normalizzato)."
  arena-name-invalid: "&cNome arena non valido. Usa lettere, numeri, trattini o underscore."
  arena-name-exists: "&cEsiste già un'arena chiamata &e%arena%&c."
  arena-created: "&aArena &e%arena%&a creata! Usa &e/tinyhunt arena set %arena% &aper definirla."
  arena-not-found: "&cNessuna arena trovata con nome &e%arena%&c."
  arena-wand-received: "&aHai ricevuto la wand per l'arena &e%arena%&a. Click sinistro = Pos1, destro = Pos2."
  arena-boundary-hit: "&cNon puoi uscire dall'arena!"
  game-start-runner: "&aSei un Runner! Sopravvivi agli Hunter."
  player-left: "&e%player% ha lasciato la partita."
  sudden-death-start: "&cSudden death! I runner saranno rivelati periodicamente."
  sudden-death-reveal: "&dPing dei runner attivo per &e%seconds%s&d!"

  state:
    waiting: "In attesa"
    countdown: "Countdown"
    running: "In corso"
    ending: "Fine partita"

  menu-title: "&6TinyHunt &7Lobby"
  menu-status-name: "&eStato lobby"
  menu-status-state: "&7Stato: &e%state%"
  menu-status-queue: "&7In coda: &a%queue%&7/&a%max%"
  menu-status-participants: "&7In partita: &c%participants%"
  menu-status-arena: "&7Arena attiva: &e%arena%"
  menu-no-arena: "Nessuna"
  menu-join-available: "&aEntra in coda"
  menu-join-available-lore: "&7Clicca per partecipare alla prossima partita."
  menu-join-leave: "&cLascia la coda"
  menu-join-leave-lore: "&7Clicca per uscire dalla coda."
  menu-join-locked: "&cPartita in corso"
  menu-join-locked-lore: "&7Attendi che la partita finisca."
  menu-join-full: "&cCoda piena"
  menu-join-full-lore: "&7Aspetta che si liberi un posto."

hud:
  scoreboard-title: "TinyHunt"
  bossbar-title: "&6Tempo rimanente: &e%time%"
  extra-match: ""
  extra-sudden-death: "Sudden death"
