name: TinyHunt
main: com.example.tinyhunt.TinyHuntPlugin
version: 0.1.0
api-version: "1.21"
authors:
  - TinyHunt Team
description: Multiplayer Hunter vs Runner minigame with configurable lobby and arena.
commands:
  tinyhunt:
    description: Gestisce il minigioco TinyHunt.
    usage: /<command>
    aliases: [th]
    permission: tinyhunt.play
  p:
    description: Chat di party
    usage: /p <messaggio>
permissions:
  tinyhunt.play:
    description: Permette di usare /tinyhunt join e /tinyhunt leave.
    default: true
  tinyhunt.admin:
    description: Permette di configurare e avviare TinyHunt.
    default: op
